-- INSERT UserNames
INSERT INTO user (username, password, name, surname, email, registration_date, imgUrl) VALUES
('Anoop', '$2a$11$dp4wMyuqYE3KSwIyQmWZFeUb7jCsHAdk7ZhFc0qGw6i5J124imQBi', 'anoop', 'anoop',
 'anoop@gmail.com', '2022-04-29', 'https://media-exp1.licdn.com/dms/image/C4D03AQHLKGpueXacHA/profile-displayphoto-shrink_800_800/0/1552729654834?e=1673481600&v=beta&t=If15e82EfT7yR6mErCuhSADUaQQWlu-QoFdjFYbjWQk'),
('demo', '$2a$11$.NNQgUXukpCuvB5nG.5XGO/NFOESgfPSqETlg5Pj2paBYmStZiucO', 'demo', 'test', 'demo@demo.com', '2022-04-29', 'https://media-exp1.licdn.com/dms/image/C4D03AQHLKGpueXacHA/profile-displayphoto-shrink_800_800/0/1552729654834?e=1673481600&v=beta&t=If15e82EfT7yR6mErCuhSADUaQQWlu-QoFdjFYbjWQk');
-- INSERT ROLES
INSERT INTO auth_user_group (username, auth_group) VALUES('herookie', 'USER');
INSERT INTO auth_user_group (username, auth_group) VALUES('herookie', 'ADMIN');
INSERT INTO auth_user_group (username, auth_group) VALUES('demo', 'USER');
-- INSERT tutors
INSERT INTO tutor (name, surname, email, description, detail, imgUrl) VALUES
( 'Man', 'Uni', 'mit@gmail.com', 'Mathematics', 'Great Teacher', 'https://yt3.ggpht.com/tBEPr-zTNXEeae7VZKSZYfiy6azzs9OHowq5ZvogJeHoVtKtEw2PXSwzMBKVR7W0MI7gyND8=s900-c-k-c0x00ffffff-no-rj'),

-- INSERT courses
INSERT INTO course (name, description, tutorId, detail, difficulty, url, imgUrl) VALUES
( 'Essential Java', 'Java course for beginners', 1, 'If you are a computer science graduate or a programmer who wants to learn Java, or someone who wants to start programming with Java, and looking for some awesome resources like books, tutorials, and online courses then you have come to the right place.', 'Easy', 'https://www.youtube.com/watch?v=eIrMbAQSU34', 'https://i.ytimg.com/vi/eIrMbAQSU34/maxresdefault.jpg'),
( 'Spring Boot Full Course', 'Full Stack Spring Boot & React (PROFESSIONAL)', 2, 'Build and Automate Deployment Like Professionals using Spring Boot | React | Maven | Docker | AWS and CICD with Github Actions', 'Easy', 'https://www.youtube.com/watch?v=xZq8wETULoM', 'https://img.youtube.com/vi/xZq8wETULoM/hqdefault.jpg'),
( 'C# Application From Start to Finish', 'Tournament Tracker Course C#',3, 'Follow along in this free course as I show you how to create an application in C# from idea through the finished product. Everything is shown on screen and in great detail. Learn how to use SQL databases, CSV text files, custom events, Linq, Lambda expressions, emailing, and more. Everything you learn will be in context of a real application.', 'Advanced', 'https://www.youtube.com/playlist?list=PLLWMQd6PeGY3t63w-8MMIjIyYS7MsFcCi', 'https://i.ytimg.com/vi/wfWxdh-_k_4/maxresdefault.jpg'),
( 'Essential Java 2', 'Java course for beginners', 1, 'If you are a computer science graduate or a programmer who wants to learn Java, or someone who wants to start programming with Java, and looking for some awesome resources like books, tutorials, and online courses then you have come to the right place.', 'Easy', 'https://www.youtube.com/watch?v=eIrMbAQSU34', 'https://i.ytimg.com/vi/eIrMbAQSU34/maxresdefault.jpg'),
( 'Spring Boot Full Course 2', 'Full Stack Spring Boot & React (PROFESSIONAL)', 2, 'Build and Automate Deployment Like Professionals using Spring Boot | React | Maven | Docker | AWS and CICD with Github Actions', 'Easy', 'https://www.youtube.com/watch?v=xZq8wETULoM', 'https://img.youtube.com/vi/xZq8wETULoM/hqdefault.jpg'),
( 'C# Application From Start to Finish 2', 'Tournament Tracker Course C#',3, 'Follow along in this free course as I show you how to create an application in C# from idea through the finished product. Everything is shown on screen and in great detail. Learn how to use SQL databases, CSV text files, custom events, Linq, Lambda expressions, emailing, and more. Everything you learn will be in context of a real application.', 'Advanced', 'https://www.youtube.com/playlist?list=PLLWMQd6PeGY3t63w-8MMIjIyYS7MsFcCi', 'https://i.ytimg.com/vi/wfWxdh-_k_4/maxresdefault.jpg'),
( 'Essential Java 3', 'Java course for beginners', 1, 'If you are a computer science graduate or a programmer who wants to learn Java, or someone who wants to start programming with Java, and looking for some awesome resources like books, tutorials, and online courses then you have come to the right place.', 'Easy', 'https://www.youtube.com/watch?v=eIrMbAQSU34', 'https://i.ytimg.com/vi/eIrMbAQSU34/maxresdefault.jpg'),
( 'Spring Boot Full Course 3', 'Full Stack Spring Boot & React (PROFESSIONAL)', 2, 'Build and Automate Deployment Like Professionals using Spring Boot | React | Maven | Docker | AWS and CICD with Github Actions', 'Easy', 'https://www.youtube.com/watch?v=xZq8wETULoM', 'https://img.youtube.com/vi/xZq8wETULoM/hqdefault.jpg'),
( 'C# Application From Start to Finish 3', 'Tournament Tracker Course C#',3, 'Follow along in this free course as I show you how to create an application in C# from idea through the finished product. Everything is shown on screen and in great detail. Learn how to use SQL databases, CSV text files, custom events, Linq, Lambda expressions, emailing, and more. Everything you learn will be in context of a real application.', 'Advanced', 'https://www.youtube.com/playlist?list=PLLWMQd6PeGY3t63w-8MMIjIyYS7MsFcCi', 'https://i.ytimg.com/vi/wfWxdh-_k_4/maxresdefault.jpg'),
( 'Essential Java 4', 'Java course for beginners', 1, 'If you are a computer science graduate or a programmer who wants to learn Java, or someone who wants to start programming with Java, and looking for some awesome resources like books, tutorials, and online courses then you have come to the right place.', 'Easy', 'https://www.youtube.com/watch?v=eIrMbAQSU34', 'https://i.ytimg.com/vi/eIrMbAQSU34/maxresdefault.jpg'),
( 'Spring Boot Full Course 4', 'Full Stack Spring Boot & React (PROFESSIONAL)', 2, 'Build and Automate Deployment Like Professionals using Spring Boot | React | Maven | Docker | AWS and CICD with Github Actions', 'Easy', 'https://www.youtube.com/watch?v=xZq8wETULoM', 'https://img.youtube.com/vi/xZq8wETULoM/hqdefault.jpg'),
( 'C# Application From Start to Finish 4', 'Tournament Tracker Course C#',3, 'Follow along in this free course as I show you how to create an application in C# from idea through the finished product. Everything is shown on screen and in great detail. Learn how to use SQL databases, CSV text files, custom events, Linq, Lambda expressions, emailing, and more. Everything you learn will be in context of a real application.', 'Advanced', 'https://www.youtube.com/playlist?list=PLLWMQd6PeGY3t63w-8MMIjIyYS7MsFcCi', 'https://i.ytimg.com/vi/wfWxdh-_k_4/maxresdefault.jpg');
